export enum ChainEnum {
  ETH = 'eth',
  BSC = 'bsc',
  BNB = 'bnb',
  POL = 'pol',
  MATIC = 'matic',
  ARB = 'arb',
  OP = 'opt',
  OPT = 'opt',
  AVAX = 'avax',
  AVA = 'avax',
  BASE = 'base',
  BAS = 'base',
  GNO = 'gnosis',
  ZK = 'zksync',
  LINEA = 'linea',
  SONIC = 'sonic',
  UNI = 'unichain',
  SOL = 'solana',
}
export enum TxChainEnum {
  ETH = 'ETH',
  BSC = 'BNB',
}

export enum SwapNetwork {
  ETH = 'ETH',
  BSC = 'BSC',
  BNB = 'BSC',
  POL = 'POL',
  MATIC = 'MATIC',
  ARB = 'ARB',
  OP = 'OPT',
  OPT = 'OPT',
  AVAX = 'AVAX',
  AVA = 'AVAX',
  BASE = 'BASE',
  BAS = 'BASE',
  GNO = 'GNO',
  ZK = 'ZK',
  LINEA = 'LINEA',
  SONIC = 'SONIC',
  UNI = 'UNI',
  SOL = 'SOL',
}

export enum ChainId {
  ETH = 1,
  BNB = 56,
  BSC = 56,
  MATIC = 137,
  POL = 137,
  ARB = 42161,
  OP = 10,
  OPT=10,
  AVAX = 43114,
  AVA= 43114,
  BASE = 8453,
  BAS=8453,
  GNO = 100,
  ZK = 324,
  LINEA = 59144,
  SONIC = 146,
  UNI = 130,
  SOL = 501,
}

export enum swapProvider {
  RANGO = 'RANGO',
  UNISWAP = 'UNISWAP',
  ONEINCH_FUSION = 'ONEINCH_FUSION',
  ONEINCH_FUSION_PLUS = 'ONEINCH_FUSION_PLUS',
  ALLBRIDGE = 'ALLBRIDGE',
}

export const ChainIdToRango: Record<number, string> = {
  1: 'ETH',
  56: 'BSC',
  137: 'POLYGON',
  42161: 'ARBITRUM',
  10: 'OPTIMISM',
  8453: 'BASE',
  43114: 'AVAX_CCHAIN',
  250: 'FANTOM',
  25: 'CRONOS',
  100: 'GNOSIS',
  1088: 'METIS',
  1101: 'POLYGONZK',
  324: 'ZKSYNC',
  59144: 'LINEA',
  534352: 'SCROLL',
  81457: 'BLAST',
  167000: 'TAIKO',
  7777777: 'ZORA',
  34443: 'MODE',
  80094: 'BERACHAIN',
};
